name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_AZURE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 104.40.186.8 >> ~/.ssh/known_hosts
        echo -e "Host *\n StrictHostKeyChecking no\n UserKnownHostsFile=/dev/null" >> ~/.ssh/config
    
    - name: Deploy to server
      run: |
        ssh Kuybi@104.40.186.8 "
          cd /var/www/kuybi-test/GroupeWeb
          
          # Pull latest changes
          git config --global --add safe.directory /var/www/kuybi-test/GroupeWeb
          git fetch --all
          git reset --hard origin/main
          
          # Create .env file using the existing .env.example template
          if [ -f .env ]; then
            rm .env
            echo ".env file removed"
          fi
          
          # Create a PHP script to generate the .env file with correct syntax
          echo '<?php
          $db_host = isset($_SERVER["DB_HOST"]) ? $_SERVER["DB_HOST"] : "";
          $db_name = isset($_SERVER["DB_NAME"]) ? $_SERVER["DB_NAME"] : "";
          $db_user = isset($_SERVER["DB_USER"]) ? $_SERVER["DB_USER"] : "";
          $db_pass = isset($_SERVER["DB_PASS"]) ? $_SERVER["DB_PASS"] : "";
          
          $env_content = "DB_HOST=\"" . $db_host . "\"\n";
          $env_content .= "DB_NAME=\"" . $db_name . "\"\n";
          $env_content .= "DB_USER=\"" . $db_user . "\"\n";
          $env_content .= "DB_PASS=\"" . $db_pass . "\"\n";
          $env_content .= "UPLOAD_PATH=\"uploads\"\n";
          
          file_put_contents(".env", $env_content);
          echo "PHP script created .env file successfully.\n";
          ?>' > create_env.php
          
          # Set environment variables and run the PHP script
          export DB_HOST='${{ secrets.DB_HOST }}'
          export DB_NAME='${{ secrets.DB_NAME }}'
          export DB_USER='${{ secrets.DB_USER }}'
          export DB_PASS='${{ secrets.DB_PASS }}'
          php create_env.php
          
          # Remove the temporary PHP script
          rm create_env.php
          
          # Install dependencies
          composer install --no-interaction --no-dev --optimize-autoloader
          
          # Clear cache if necessary (for frameworks like Laravel)
          if [ -f artisan ]; then
            php artisan cache:clear
            php artisan config:cache
          fi
          
          # Set appropriate permissions
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;
          
          # Make sure upload directory exists and is writable
          mkdir -p uploads
          chmod -R 775 uploads
          
          # Restart Apache
          sudo systemctl restart apache2
          
          echo 'Deployment completed successfully'
        "
